### ISSUE TITLE
Error: 'xml_find_first' is not an exported object from 'namespace:xml2'

### ISSUE THREAD

**Issue by rellan** [jennybc/googlesheets#264]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
This means that your version of `xml2` is not recent enough for your version of `googlesheets`. I'm not sure how that happened because the minimum `xml2` version is listed in DESCRIPTION. In any case, updating `xml2` should fix it:

```r
install.packages("xml2")
```

**Comment by rellan** [comment]
Thanks, Jenny,

I did what you suggested but I still get the same error.

RRA

**Comment by jennybc** [comment]
Will you restart R and show me the output of `devtools::session_info("googlesheets")`? And make the same calls that have triggered the error above?

**Comment by rellan** [comment]
See below the output after restarting. Still the same error.
Session info -----------------------------------------------------------------
 setting  value                       
 version  R version 3.2.4 (2016-03-16)
 system   x86_64, darwin14.5.0        
 ui       RStudio (0.99.902)          
 language (EN)                        
 collate  C                           
 tz       America/Mexico_City         
 date     2016-07-09                  
Packages ---------------------------------------------------------------------
 package      * version    date       source                               
 BH             1.60.0-1   2015-12-28 CRAN (R 3.2.3)                       
 DBI            0.3.1      2014-09-24 CRAN (R 3.2.0)                       
 R6             2.1.2      2016-01-26 CRAN (R 3.2.3)                       
 Rcpp           0.12.4     2016-03-26 CRAN (R 3.2.4)                       
 assertthat     0.1        2013-12-06 CRAN (R 3.2.0)                       
 cellranger     1.0.0      2015-06-20 CRAN (R 3.2.0)                       
 curl           0.9.6      2016-02-17 CRAN (R 3.2.3)                       
 dplyr          0.4.3      2015-09-01 CRAN (R 3.2.0)                       
 googlesheets   0.2.1.9000 2016-07-09 Github (jennybc/googlesheets@de407a8)
 httr           1.1.0      2016-01-28 CRAN (R 3.2.3)                       
 jsonlite       0.9.19     2015-11-28 CRAN (R 3.2.2)                       
 lazyeval       0.1.10     2015-01-02 CRAN (R 3.2.0)                       
 magrittr       1.5        2014-11-22 CRAN (R 3.2.0)                       
 mime           0.4        2015-09-03 CRAN (R 3.2.0)                       
 openssl        0.9.2      2016-02-26 CRAN (R 3.2.3)                       
 purrr          0.2.1      2016-02-13 CRAN (R 3.2.3)                       
 readr          0.2.2      2015-10-22 CRAN (R 3.2.0)                       
 stringi        1.0-1      2015-10-22 CRAN (R 3.2.0)                       
 stringr        1.0.0      2015-04-30 CRAN (R 3.2.0)                       
 tidyr          0.4.1      2016-02-05 CRAN (R 3.2.3)                       
 xml2           0.1.2      2015-09-01 CRAN (R 3.2.0)

**Comment by jennybc** [comment]
Please see the first comment above about installing the current CRAN version of xml2. That is your problem. It should be at v1.0.0.

**Comment by chainsawriot** [comment]
I have the same issue and it can solved by updating the `httr` to 1.2.1 and `xml2` to 1.0.0.
